services:
  rabbitmq:
    image: rabbitmq:4.2.4
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shared-net
      - rabbitmq-net
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq


  vcenter-worker:
    build:
      context: ./vCenter
      dockerfile: Dockerfile

    container_name: vcenter-worker
    env_file:
      - vCenter/.env

    networks:
      - rabbitmq-net
    depends_on:
      - rabbitmq
    volumes:
      - ./vCenter:/code



networks:
  shared-net:
    external: true
    name: shared-bridge

  rabbitmq-net:
    external: true
    name: shared-rabbitmq-workers

volumes:
  rabbitmq-data:
