services:
  db:
    image: postgres:17.9
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db
    networks:
      - shared-net
      - rabbitmq-net
        
  fast-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - shared-net
    env_file:
      - .env
    volumes:
      - ./code:/FastAPI
    depends_on:
      - db


networks:
  shared-net:
    external: true
    name: shared-bridge

  rabbitmq-net:
    external: true
    name: shared-rabbitmq-workers


volumes:
  postgres_data: {}

