from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
import subprocess
import os
import ast
import json
import asyncio
import asyncpg
import re
from datetime import datetime
from dotenv import load_dotenv




PG_PWD = os.getenv("PG_PWD")
app = FastAPI()

class AppsmithPayload(BaseModel):
    message: str

class VMCreation(BaseModel):
    owner: str
    vm_name: str
    folder: str
    template: str
    portgroup: str

    is_windows_image: str

    ram_size: int
    cpu_number: int
    disk_size_gb: list

    shutdown_date: datetime
    deletion_date: datetime



@app.post('/vm')
def create_vm(payload: VMCreation):
    try:
        import uuid
        random_uuid = str(uuid.uuid4())
        
        cmd = ["terraform", "-chdir=Terraform", "init"]
        init_result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        
        cmd = ["terraform", "-chdir=Terraform/", "workspace", "new", f"{random_uuid}"]
        workspace_result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    
        async def insert_db_record():
            conn = await asyncpg.connect(user='admin', password=PG_PWD, database='postgres', host='postgres')
            try:
                query = """
                INSERT INTO terraform_remote_state.state_metadata (
                    state_key, owner, folder, portgroup, template_used, 
                    cpu_cores, ram_mb, disk_gb, shutdown_date, deletion_date, status
                ) VALUES (
                    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'provisioning'
                )
                """
            
                await conn.execute(
                    query, 
                    random_uuid,                    # Maps to $1 (State key is the generated UUID)
                    payload.owner,                  # Maps to $2 (Ensure 'owner' exists in your VMCreation model)
                    payload.folder,                 # Maps to $3
                    payload.portgroup,              # Maps to $4
                    payload.template,               # Maps to $5 (Matches your terraform var)
                    payload.cpu_number,             # Maps to $6 (Matches your terraform var)
                    payload.ram_size,               # Maps to $7 (Matches your terraform var)
                    int(payload.disk_size_gb[0]),   # Maps to $8 (Matches your terraform var)
                    payload.shutdown_date,          # Maps to $9 (Ensure this exists in your model)
                    payload.deletion_date           # Maps to $10 (Ensure this exists in your model)
                )
            finally:
                await conn.close()

        asyncio.run(insert_db_record())
        

        disk_size_gb = json.dumps(payload.disk_size_gb)
        cmd2 = ["terraform", "-chdir=Terraform", "apply", "-no-color",
                 f"-var=vm_name={payload.vm_name}",
                 f"-var=folder={payload.folder}",
                 f"-var=template={payload.template}",
                 f"-var=portgroup={payload.portgroup}",
                 f"-var=is_windows_image={payload.is_windows_image}",
                 f"-var=ram_size={payload.ram_size}",
                 f"-var=cpu_number={payload.cpu_number}",
                 f"-var=disk_size_gb={disk_size_gb}",
                  "-auto-approve"]
        
        apply_result = subprocess.run(cmd2, capture_output=True, text=True, check=True)

        cmd_output = ["terraform", "-chdir=Terraform", "output", "-json", "uuid"]
        output_result = subprocess.run(cmd_output, capture_output=True, text=True, check=True)
        uuid_list = json.loads(output_result.stdout)
        real_uuid = uuid_list[0]
        if real_uuid:
            # 2. Save the REAL BIOS UUID to the new column
            async def save_vcenter_uuid():
                conn = await asyncpg.connect(os.getenv("PG_CONN_STR"))
                try:
                    await conn.execute(
                        "UPDATE terraform_remote_state.state_metadata SET vcenter_uuid = $1 WHERE state_key = $2",
                        real_uuid, random_uuid
                    )
                    await conn.execute(
                        "UPDATE terraform_remote_state.state_metadata SET status = 'active'"
                    )
                finally:
                    await conn.close()
            
        asyncio.run(save_vcenter_uuid())

        return {"status": "success", "created": f"{apply_result.stdout}"}
    except subprocess.CalledProcessError as e:
        # e.stderr contains the exact red text error generated by Terraform
        # e.stdout contains the standard output up until the point of failure
        error_output = e.stderr if e.stderr else e.stdout
        
        return {
            "status": "failed", 
            "message": f"Terraform command failed (Exit Code: {e.returncode})", 
            "command_result": error_output
        }
    
    except Exception as e:
        # This acts as a fallback for database timeouts or Python syntax errors
        return {
            "status": "failed", 
            "message": "Internal System Error", 
            "command_result": str(e)
        }


@app.get("/list-folders")
def list_folders():
    try:
        cmd = ["python3", "list-folders.py"]
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True
        )

        raw_output = result.stdout.rstrip()
        parsed_folders = ast.literal_eval(raw_output)
        return {"status": "success", "folders": parsed_folders}
    except Exception as e:
        return {f"Error: \n{e}\nOutput: {result}"}
    

@app.get("/list-templates")
def list_templates():
    try:
        cmd = ["python3", "list-templates.py"]
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True
        )

        raw_output = result.stdout.rstrip()
        parsed_templates = ast.literal_eval(raw_output)
        return {"status": "success", "templates": parsed_templates}
    except Exception as e:
        return {"status": "error", "Error message": e}



@app.get("/list-portgroups")
def list_portgroups():
    try:
        cmd = ["python3", "list-portgroups.py"]
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True
        )

        raw_output = result.stdout.rstrip()
        parsed_portgroups = ast.literal_eval(raw_output)
        return {"status": "success", "portgroups": parsed_portgroups}
    except Exception as e:
        return {"status": "error", "Error message": e}


@app.get('/vm-ip')
def get_ip():
    try:
        cmd = ["terraform", "-chdir=Terraform",
               "output", "ip"]
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True
        )

        raw_output = result.stdout.rstrip()
        parsed_ip = ast.literal_eval(raw_output)
        return {"status": "success", "ip": parsed_ip}
    except Exception as e:
        return {"status": "error", "Error message": e}







# TESTS
@app.post("/run-test-script")
def execute_test_script(payload: AppsmithPayload):
    cmd = ["python3", "test-script.py", payload.message]

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        check=True
    )
    return {"status": "success", "script_output": result.stdout.strip()}

@app.get('/list')
def execute_list_script():
    cmd = ["python3", "list-script.py"]
    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        check=True

    )
    parsed_list = result.stdout.rstrip()
    return  {"status": "success", "items": parsed_list}

